# Generated by Django 6.0.2 on 2026-02-10 05:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="AI-generated project brief"),
                ),
                ("github_repo_url", models.URLField()),
                (
                    "github_repo_full_name",
                    models.CharField(
                        help_text="Format: username/repository", max_length=255
                    ),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        default=list,
                        help_text="List of technologies: ['Django', 'PostgreSQL', 'Redis']",
                    ),
                ),
                ("architecture_guidelines", models.TextField(blank=True)),
                ("coding_standards", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.IntegerField(
                        default=40,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "acceptance_criteria",
                    models.JSONField(
                        default=list, help_text="List of criteria that must be met"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Sequential order within the project"
                    ),
                ),
                (
                    "github_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("github_pr_number", models.IntegerField(blank=True, null=True)),
                ("github_pr_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("revision_required", "Revision Required"),
                            ("approved", "Approved"),
                            ("merged", "Merged"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "focus_areas",
                    models.JSONField(
                        default=list,
                        help_text="Skill areas to focus on: ['validation', 'security', 'error_handling']",
                    ),
                ),
                (
                    "hints",
                    models.TextField(
                        blank=True, help_text="AI-generated hints if intern struggles"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True, related_name="dependent_tasks", to="projects.task"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["project", "order"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_number", models.IntegerField()),
                ("commit_sha", models.CharField(max_length=40)),
                (
                    "files_changed",
                    models.JSONField(
                        default=list, help_text="List of file paths that were modified"
                    ),
                ),
                (
                    "diff_content",
                    models.TextField(help_text="Full diff for AI context"),
                ),
                (
                    "ai_feedback",
                    models.TextField(help_text="Markdown-formatted feedback from AI"),
                ),
                (
                    "review_decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("request_changes", "Request Changes"),
                            ("comment", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "issues_found",
                    models.JSONField(
                        default=list,
                        help_text="Structured list of issues with type, severity, file, line, message",
                    ),
                ),
                (
                    "strengths_identified",
                    models.JSONField(
                        default=list, help_text="Positive aspects of the code"
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(default=list, help_text="Improvement suggestions"),
                ),
                (
                    "code_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("posted_to_github", models.BooleanField(default=False)),
                ("github_review_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "code_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "code_context",
                    models.JSONField(
                        blank=True,
                        help_text="Relevant code snippets referenced in the message",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="projects.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="messages_convers_3ebb41_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "-assigned_at"], name="projects_user_id_33a8d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_status_6303d7_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "order"], name="tasks_project_42db2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "assigned_at"], name="tasks_status_67097b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["github_pr_number"], name="tasks_github__20694d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("project", "order")},
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="conversatio_user_id_e93dff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(
                fields=["task", "-created_at"], name="code_review_task_id_9ad646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(
                fields=["pr_number"], name="code_review_pr_numb_e97d0b_idx"
            ),
        ),
    ]
