# Generated by Django 6.0.2 on 2026-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="GitHub event type: pull_request, push, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Event action: opened, synchronize, closed, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Full webhook payload from GitHub"),
                ),
                (
                    "signature",
                    models.CharField(
                        help_text="HMAC signature for verification", max_length=255
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["processed", "created_at"],
                        name="webhook_eve_process_8c85e6_idx",
                    ),
                    models.Index(
                        fields=["event_type", "action"],
                        name="webhook_eve_event_t_c0872d_idx",
                    ),
                ],
            },
        ),
    ]
